name: Cek Kode HTML(Windows)

on:
  push:
    branches:
      - main
  pull_request: 

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Periksa HTML
        run: htmlhint "**/*.html"

      - name: Periksa CSS
        run: stylelint "**/*.css"
